name: Bug
description: If a bug/glitch was found somewhere in the game while playing/modding.
labels: [Bug]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your issue here."
    validations:
      required: true

  - type: textarea
    id: terminal
    attributes:
      label: "Command Prompt/Terminal logs (if existing)"
      render: bash
    validations:
      required: false

  - type: dropdown
    id: modding
    attributes:
      label: "How did you modify the game?"
      options:
        - Scripting
        - Compiled from Source
    validations:
      required: true

  - type: dropdown
    id: btarget
    attributes:
      label: "What is your build target?"
      options:
        - "Windows"
        - "Linux"
        - "MacOS"
        - "Neko, HashLink, or other build system"
    validations:
      required: true

  - type: input
    id: buildsummary
    attributes:
      label: "Did you edit anything in this build? If so, mention or summarize your changes."
      placeholder: "Yes, I edited Settings.hx and tried to add a new setting"
    validations:
      required: true
