name: Missing Documentation
description: If a comment somewhere is missing, or the wiki is documented wrong.
body:
  - type: textarea
    id: description
    attributes:
      label: "Where?"
    validations:
      required: true
