name: Missing/Incorrect Documentation
description: If you'd like to report incorrect or missing docs.
labels: [Documentation]
body:
  - type: textarea
    id: description
    attributes:
      label: "Where's the problem?"
    validations:
      required: true
