name: Build

on:
  push:
    branches: [main, drilly-plush]
  pull_request:
    branches: [main, drilly-plush]
  workflow_dispatch:

jobs:
  cancel_previous_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

  Linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.1
      - name: Install Libraries
        run: |
          sudo apt-get install libvlc-dev
          sudo apt-get install libvlccore-dev
          haxelib setup ~/haxelib
          chmod +x ./_setup/unix.sh
          sh ./_setup/unix.sh
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: |
          echo "@echo off" > "yes.bat"
          echo ":loop" >> "yes.bat"
          echo "echo y" >> "yes.bat"
          echo "goto loop" >> "yes.bat"

          yes | haxelib run lime build cpp --app-version="4.0.0-${{ github.run_id}}"

      - name: Upload Build
        uses: actions/upload-artifact@v4.3.4
        with:
          name: Linux
          path: _export/release/linux/bin
  Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.1
      - name: Install Libraries
        run: |
          haxelib setup C:/haxelib
          .\"_setup/windows.bat"
        shell: cmd
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile HXCPP
        run: .\"_setup/build-hxcpp.bat"
      - name: Compile
        run: haxelib run lime build cpp --app-version="4.0.0-${{ github.run_id}}"
      - name: Upload Build
        uses: actions/upload-artifact@v4.3.4
        with:
          name: Windows
          path: _export/release/windows/bin
  MacOS:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.1
      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          chmod +x ./_setup/unix.sh
          sh ./_setup/unix.sh
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: yes | haxelib run lime build mac --app-version="4.0.0-${{ github.run_id}}"
      - name: Upload Build
        uses: actions/upload-artifact@v4.3.4
        with:
          name: MacOS
          path: _export/release/macos/bin
